export const API_URL = process.env.EXPO_PUBLIC_API_URL || 'http://127.0.0.1:3000';
let authToken='';
export const setAuthToken=(v:string)=>{authToken=v};
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_URL}${path}`, { ...init, headers: { 'Content-Type':'application/json', ...(authToken?{Authorization:`Bearer ${authToken}`}:{ }), ...(init?.headers || {}) } }); const body = await response.json().catch(()=>({})); if(!response.ok) throw new Error(body?.message || `Request failed (${response.status})`); return body as T; }
export const driverApi = {
  aiAssist:(body:any)=>request<any>('/v1/ai/driver/assist',{method:'POST',body:JSON.stringify(body)}),
  aiHistory:(userId:string)=>request<any[]>(`/v1/ai/users/${userId}/history`),
  registerRiskDevice:(body:any)=>request<any>('/v1/risk/devices/register',{method:'POST',body:JSON.stringify(body)}),
  riskSummary:(userId:string)=>request<any>(`/v1/risk/users/${userId}/summary`),
  registerPushDevice:(body:any)=>request<any>('/v1/notifications/devices/register',{method:'POST',body:JSON.stringify(body)}),
  notificationHistory:(userId:string)=>request<any[]>(`/v1/notifications/users/${userId}/history`),
  register:(body:any)=>request<any>('/v1/auth/register',{method:'POST',body:JSON.stringify({...body,role:'DRIVER'})}),
  login:(email:string,password:string)=>request<any>('/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})}),
  profile:(userId:string)=>request<any>(`/v1/users/${userId}/profile`),
  connectAccount:(userId:string)=>request<any>(`/v1/payments/connect/drivers/${userId}/account`,{method:'POST'}),
  connectOnboardingLink:(userId:string)=>request<any>(`/v1/payments/connect/drivers/${userId}/onboarding-link`,{method:'POST'}),
  connectStatus:(userId:string)=>request<any>(`/v1/payments/connect/drivers/${userId}/status`),
  earningsSummary:(userId:string,period:'DAY'|'WEEK'|'MONTH'='WEEK')=>request<any>(`/v1/earnings/drivers/${userId}/summary?period=${period}`),
  earningsHistory:(userId:string)=>request<any[]>(`/v1/earnings/drivers/${userId}/history?limit=100`),
  bonusProgress:(userId:string)=>request<any[]>(`/v1/earnings/drivers/${userId}/bonuses`),
  refreshBonuses:(userId:string)=>request<any>(`/v1/earnings/drivers/${userId}/refresh-bonuses`,{method:'POST'}),
  documents:(userId:string)=>request<any[]>(`/v1/drivers/${userId}/documents`),
  compliance:(userId:string)=>request<any>(`/v1/drivers/${userId}/compliance`),
  addDocument:(userId:string,body:any)=>request<any>(`/v1/drivers/${userId}/documents`,{method:'POST',body:JSON.stringify(body)}),
  availability:(userId:string,availability:'ONLINE'|'OFFLINE')=>request<any>(`/v1/drivers/${userId}/availability`,{method:'PATCH',body:JSON.stringify({availability})}),
  location:(userId:string,lat:number,lng:number,accuracyMeters=10)=>request<any>(`/v1/drivers/${userId}/location`,{method:'PATCH',body:JSON.stringify({lat,lng,accuracyMeters})}),
  candidates:(tripId:string)=>request<any[]>(`/v1/dispatch/trips/${tripId}/candidates?radiusMiles=20&limit=10`),
  nextOffer:(driverUserId:string)=>request<any|null>(`/v1/dispatch/drivers/${driverUserId}/next-offer?radiusMiles=20&ttlSeconds=20`),
  rejectOffer:(offerId:string,driverUserId:string)=>request<any>(`/v1/dispatch/offers/${offerId}/reject`,{method:'POST',body:JSON.stringify({driverUserId})}),
  accept:(tripId:string,driverUserId:string,vehicleId:string,offerId?:string)=>request<any>(`/v1/trips/${tripId}/accept`,{method:'POST',body:JSON.stringify({driverUserId,vehicleId,offerId})}),
  transition:(tripId:string,type:'arriving'|'arrived'|'start'|'complete',actorUserId:string)=>request<any>(`/v1/trips/${tripId}/${type}`,{method:'PATCH',body:JSON.stringify({actorUserId})}),
  getTrip:(tripId:string)=>request<any>(`/v1/trips/${tripId}`),
  waitStatus:(tripId:string)=>request<any>(`/v1/trips/${tripId}/wait-status`),
  noShow:(tripId:string,actorUserId:string)=>request<any>(`/v1/trips/${tripId}/no-show`,{method:'POST',body:JSON.stringify({actorUserId})}),
  cancelTrip:(tripId:string,actorUserId:string)=>request<any>(`/v1/trips/${tripId}/cancel`,{method:'POST',body:JSON.stringify({actor:'DRIVER',actorUserId,reason:'DRIVER_REQUEST'})}),
  sos:(tripId:string,body:any)=>request<any>(`/v1/safety/trips/${tripId}/sos`,{method:'POST',body:JSON.stringify(body)}),
  createSafetyShareLink:(tripId:string,userId:string)=>request<any>(`/v1/safety/trips/${tripId}/share-links`,{method:'POST',body:JSON.stringify({userId,expiresInMinutes:240})}),
  createSupportTicket:(body:any)=>request<any>('/v1/support/tickets',{method:'POST',body:JSON.stringify(body)}),
  reportLostItem:(body:any)=>request<any>('/v1/support/lost-items',{method:'POST',body:JSON.stringify(body)}),
  reportIncident:(tripId:string,body:any)=>request<any>(`/v1/safety/trips/${tripId}/incidents`,{method:'POST',body:JSON.stringify(body)}),
  rateTrip:(tripId:string,fromUserId:string,stars:number,comment='')=>request<any>(`/v1/trips/${tripId}/rating`,{method:'POST',body:JSON.stringify({fromUserId,stars,comment})}),
  route:(origin:any,destination:any)=>request<any>('/v1/routing/route',{method:'POST',body:JSON.stringify({origin:{lat:origin.latitude,lng:origin.longitude},destination:{lat:destination.latitude,lng:destination.longitude}})}),
};
