import React,{useEffect,useState}from'react';
import{API_URL,adminApi,setAdminToken}from'./api';

const Card=({title,value}:{title:string,value:any})=><div className="metric"><div>{title}</div><strong>{value??0}</strong></div>;
const Btn=({children,onClick,danger=false}:{children:any,onClick:()=>void,danger?:boolean})=><button className={danger?'danger':''} onClick={onClick}>{children}</button>;

export default function App(){
 const[email,setEmail]=useState('admin@uride.local'),[password,setPassword]=useState('Password123!'),[admin,setAdmin]=useState<any>(null),[metrics,setMetrics]=useState<any>(null);
 const[drivers,setDrivers]=useState<any[]>([]),[aiBrief,setAiBrief]=useState<any>(null),[aiSupport,setAiSupport]=useState<Record<string,string>>({}),[pricingRules,setPricingRules]=useState<any[]>([]),[bonusCampaigns,setBonusCampaigns]=useState<any[]>([]),[riskCases,setRiskCases]=useState<any[]>([]),[selectedRisk,setSelectedRisk]=useState<any>(null),[selectedSafety,setSelectedSafety]=useState<any>(null),[documents,setDocuments]=useState<any[]>([]),[trips,setTrips]=useState<any[]>([]),[tickets,setTickets]=useState<any[]>([]),[incidents,setIncidents]=useState<any[]>([]),[refunds,setRefunds]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[tab,setTab]=useState('overview'),[message,setMessage]=useState('');
 const run=async(fn:()=>Promise<void>)=>{try{setMessage('');await fn()}catch(e:any){setMessage(e.message||'Error')}};
 const login=()=>run(async()=>{const r=await adminApi.login(email,password);if(r.user.role!=='ADMIN')throw new Error('Esta cuenta no tiene rol ADMIN');setAdminToken(r.accessToken);setAdmin(r.user);});
 const refresh=()=>run(async()=>{setMetrics(await adminApi.dashboard());setDrivers(await adminApi.pendingDrivers());setDocuments(await adminApi.pendingDocuments());setTrips(await adminApi.activeTrips());setTickets(await adminApi.tickets());setIncidents(await adminApi.incidents());setPricingRules(await adminApi.pricingRules());setBonusCampaigns(await adminApi.bonusCampaigns());setRiskCases(await adminApi.riskCases());setRefunds(await adminApi.refunds());setAudit(await adminApi.audit())});
 useEffect(()=>{if(admin)refresh()},[admin]);
 const setDriver=(id:string,status:string)=>run(async()=>{await adminApi.driverStatus(id,status,admin.id);await refresh()});
 const setVehicle=(id:string,status:string)=>run(async()=>{await adminApi.vehicleStatus(id,status,admin.id);await refresh()});
 const setDocument=(id:string,status:string)=>run(async()=>{await adminApi.documentStatus(id,status,admin.id,status==='REJECTED'?'Corrección requerida':undefined);await refresh()});
 const setTicket=(id:string,status:string)=>run(async()=>{await adminApi.ticketStatus(id,status,admin.id);await refresh()});
 const setIncident=(id:string,status:string)=>run(async()=>{await adminApi.incidentStatus(id,status,admin.id,status==='RESOLVED'?'Caso revisado por Operations':undefined);await refresh()});
 const safetyAction=(id:string,action:string,note?:string)=>run(async()=>{await adminApi.incidentAction(id,action,admin.id,note);await refresh();if(selectedSafety?.id===id)setSelectedSafety({...selectedSafety,...await adminApi.safetyMonitor(selectedSafety.tripId)})});
 const openSafetyMonitor=(tripId:string,id:string)=>run(async()=>{const snap=await adminApi.safetyMonitor(tripId);setSelectedSafety({...snap,id,tripId})});
 const loadAiBrief=()=>run(async()=>{setAiBrief(await adminApi.aiOperationsBrief())});
 const supportAi=(ticketId:string)=>run(async()=>{const r=await adminApi.aiSupportAssist(ticketId);setAiSupport(v=>({...v,[ticketId]:r.answer}))});
 const addDefaultPricing=()=>run(async()=>{await adminApi.createPricingRule({serviceType:'STANDARD',baseFare:2.50,perMile:1.65,perMinute:0.28,bookingFee:1.50,minimumFare:7.00,platformCommissionRate:0.20,adminUserId:admin.id});await refresh()});
 const addSampleBonus=()=>run(async()=>{const startsAt=new Date();const endsAt=new Date(Date.now()+7*24*60*60*1000);await adminApi.createBonusCampaign({name:'20 viajes esta semana',description:'Bono Foundation configurable',targetTrips:20,rewardAmount:50,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),adminUserId:admin.id});await refresh()});
 const openRisk=(userId:string)=>run(async()=>{setSelectedRisk(await adminApi.riskUser(userId))});
 const reviewRisk=(caseId:string,decision:string)=>run(async()=>{await adminApi.riskReview(caseId,{decision,adminUserId:admin.id,restrictionHours:24,reviewNote:`${decision} por revisión manual de Operations`});await refresh();setSelectedRisk(null)});
 const setRefund=(id:string,status:string)=>run(async()=>{await adminApi.refundStatus(id,status,admin.id);await refresh()});
 if(!admin)return <main className="login"><section><h1>URIDE</h1><h2>Operations</h2><p>MVP v1.0.0 Pilot</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/><button onClick={login}>Entrar al panel</button><small>API: {API_URL}</small>{message&&<div className="error">{message}</div>}</section></main>;
 return <div className="app"><aside><h1>URIDE</h1><span>Operations</span>{['overview','drivers','documents','trips','support','safety','ai','finance','risk','refunds','audit'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x.toUpperCase()}</button>)}<button onClick={refresh}>ACTUALIZAR</button></aside><main><header><div><h2>Centro de Operaciones</h2><p>{admin.email}</p></div>{message&&<b className="error">{message}</b>}</header>
 {tab==='overview'&&<><div className="metrics"><Card title="Viajes activos" value={metrics?.activeTrips}/><Card title="Drivers conectados" value={metrics?.onlineDrivers}/><Card title="Drivers pendientes" value={metrics?.pendingDrivers}/><Card title="Vehículos pendientes" value={metrics?.pendingVehicles}/><Card title="Documentos pendientes" value={metrics?.pendingDocuments}/><Card title="Documentos por vencer" value={metrics?.expiringDocuments}/><Card title="Tickets abiertos" value={metrics?.openTickets}/><Card title="Incidentes" value={metrics?.openIncidents}/><Card title="SOS/Críticos" value={metrics?.criticalIncidents}/><Card title="Sin reconocer" value={metrics?.unacknowledgedIncidents}/><Card title="Incidente más antiguo (min)" value={metrics?.oldestOpenMinutes}/><Card title="Casos Risk" value={metrics?.openRiskCases}/><Card title="Ganancias Driver disponibles" value={`$${Number(metrics?.availableDriverEarnings||0).toFixed(2)}`}/><Card title="Reembolsos" value={metrics?.pendingRefunds}/><Card title="Reservas" value={metrics?.scheduledTrips}/></div><section className="panel"><h3>Estado operacional</h3><p>Dashboard generado: {metrics?.generatedAt?new Date(metrics.generatedAt).toLocaleString():'—'}</p></section></>}
 {tab==='drivers'&&<section className="panel"><h3>Conductores y vehículos pendientes</h3>{drivers.map(d=><article key={d.id}><div><strong>{d.firstName} {d.lastName}</strong><p>{d.user.email} • Driver: {d.status}</p></div><div className="actions"><Btn onClick={()=>setDriver(d.id,'APPROVED')}>Aprobar Driver</Btn><Btn danger onClick={()=>setDriver(d.id,'REJECTED')}>Rechazar</Btn></div>{d.vehicles.map((v:any)=><div className="vehicle" key={v.id}><span>{v.year} {v.make} {v.model} • {v.plate} • {v.status}</span><div className="actions"><Btn onClick={()=>setVehicle(v.id,'APPROVED')}>Aprobar vehículo</Btn><Btn danger onClick={()=>setVehicle(v.id,'REJECTED')}>Rechazar</Btn></div></div>)}</article>)}</section>}
 {tab==='documents'&&<section className="panel"><h3>Documentos pendientes</h3>{documents.map(d=><article key={d.id}><strong>{d.type} • {d.status}</strong><p>{d.driverProfile.firstName} {d.driverProfile.lastName} • {d.driverProfile.user.email}</p><small>{d.vehicle?`${d.vehicle.year} ${d.vehicle.make} ${d.vehicle.model} • ${d.vehicle.plate}`:'Documento del conductor'}{d.expiresAt?` • vence ${new Date(d.expiresAt).toLocaleDateString()}`:''}</small><div className="actions"><Btn onClick={()=>setDocument(d.id,'APPROVED')}>Aprobar documento</Btn><Btn danger onClick={()=>setDocument(d.id,'REJECTED')}>Solicitar corrección</Btn></div></article>)}</section>}
 {tab==='trips'&&<section className="panel"><h3>Viajes activos</h3>{trips.map(t=><article key={t.id}><strong>{t.status}</strong><p>{t.pickupAddress} → {t.destinationAddress}</p><small>{t.driver?`${t.driver.firstName} ${t.driver.lastName}`:'Buscando conductor'} {t.vehicle?`• ${t.vehicle.plate}`:''}</small></article>)}</section>}
 {tab==='support'&&<section className="panel"><h3>Cola de soporte</h3>{tickets.map(t=><article key={t.id}><strong>{t.priority} • {t.category}</strong><p>{t.subject} — {t.status}</p><div className="actions"><Btn onClick={()=>supportAi(t.id)}>URide AI: resumir</Btn><Btn onClick={()=>setTicket(t.id,'IN_PROGRESS')}>Tomar caso</Btn><Btn onClick={()=>setTicket(t.id,'RESOLVED')}>Resolver</Btn></div>{aiSupport[t.id]&&<p className="aiAnswer">{aiSupport[t.id]}</p>}</article>)}</section>}
 {tab==='safety'&&<section className="panel"><h3>Centro de Seguridad</h3><p>Las acciones “Contacto informado” y “Emergencias contactadas” registran una acción realizada por el operador; esta Foundation no llama automáticamente al 911 ni envía SMS externos.</p>{incidents.map(i=><article className={i.type==='SOS'?'sos':''} key={i.id}><strong>{i.priority} • {i.type} • {i.status}</strong><p>Viaje {i.tripId} {i.message?`• ${i.message}`:''}</p><small>Escalación: {i.escalationLevel||0} • Operador: {i.assignedAdminUserId||'sin asignar'} {i.emergencyServicesContactedAt?'• emergencias registradas':''}</small><div className="actions"><Btn onClick={()=>openSafetyMonitor(i.tripId,i.id)}>Monitorear viaje</Btn><Btn onClick={()=>setIncident(i.id,'ACKNOWLEDGED')}>Reconocer</Btn><Btn onClick={()=>safetyAction(i.id,'ESCALATED','Prioridad elevada por Operations')}>Escalar</Btn><Btn onClick={()=>safetyAction(i.id,'TRUSTED_CONTACT_NOTIFIED','Operador confirmó contacto con contacto de confianza')}>Contacto informado</Btn><Btn danger onClick={()=>safetyAction(i.id,'EMERGENCY_SERVICES_CONTACTED','Operador confirmó contacto manual con servicios de emergencia')}>Emergencias contactadas</Btn><Btn onClick={()=>setIncident(i.id,'RESOLVED')}>Resolver</Btn></div></article>)}{selectedSafety&&<article className="monitor"><h3>Monitoreo del viaje {selectedSafety.tripId}</h3><p>Estado: {selectedSafety.status}</p><p>{selectedSafety.pickupAddress} → {selectedSafety.destinationAddress}</p><p>Passenger: {selectedSafety.passenger?.email||'—'} • Driver: {selectedSafety.driver?`${selectedSafety.driver.firstName} ${selectedSafety.driver.lastName}`:'—'} • Vehículo: {selectedSafety.vehicle?`${selectedSafety.vehicle.color} ${selectedSafety.vehicle.make} ${selectedSafety.vehicle.model} ${selectedSafety.vehicle.plate}`:'—'}</p><p>Última ubicación: {selectedSafety.locations?.[0]?`${selectedSafety.locations[0].lat.toFixed(5)}, ${selectedSafety.locations[0].lng.toFixed(5)} • ${new Date(selectedSafety.locations[0].recordedAt).toLocaleString()}`:'sin GPS reciente'}</p><p>Incidentes registrados: {selectedSafety.safetyIncidents?.length||0} • puntos GPS recientes: {selectedSafety.locations?.length||0}</p></article>}</section>}
 {tab==='ai'&&<section className="panel"><h3>URide AI — Operations Intelligence</h3><p>Esta capa resume y recomienda. No puede ejecutar reembolsos, suspensiones, cobros, aprobaciones, cambios de Pricing ni acciones de emergencia.</p><div className="actions"><Btn onClick={loadAiBrief}>Generar resumen operativo</Btn></div>{aiBrief&&<article className="monitor"><strong>Resumen operativo</strong><p>{aiBrief.answer}</p><small>Viajes activos: {aiBrief.metrics?.activeTrips||0} • Drivers conectados: {aiBrief.metrics?.onlineDrivers||0} • Seguridad crítica: {aiBrief.metrics?.criticalSafety||0} • Risk HIGH/CRITICAL: {aiBrief.metrics?.highRisk||0} • Tickets: {aiBrief.metrics?.openTickets||0}</small></article>}<h3>Support Copilot</h3><p>En la pestaña SUPPORT, el botón “URide AI: resumir” analiza el contexto del ticket y recomienda el siguiente paso sin ejecutar la decisión.</p></section>}
 {tab==='finance'&&<section className="panel"><h3>Pricing & Driver Earnings</h3><p>Las reglas activas controlan tarifa base, millas, minutos, booking fee, mínimo y comisión de URide. Al crear una nueva regla STANDARD, la anterior se desactiva.</p><div className="actions"><Btn onClick={addDefaultPricing}>Crear regla STANDARD 20%</Btn><Btn onClick={addSampleBonus}>Crear bono de prueba 20 viajes / $50</Btn></div><h3>Reglas de precio</h3>{pricingRules.map(r=><article key={r.id}><strong>{r.serviceType} • {r.isActive?'ACTIVA':'INACTIVA'}</strong><p>Base ${Number(r.baseFare).toFixed(2)} • ${Number(r.perMile).toFixed(2)}/mi • ${Number(r.perMinute).toFixed(2)}/min • Booking ${Number(r.bookingFee).toFixed(2)} • Mínimo ${Number(r.minimumFare).toFixed(2)}</p><small>Comisión URide: {(Number(r.platformCommissionRate)*100).toFixed(1)}%</small><div className="actions"><Btn onClick={()=>run(async()=>{await adminApi.pricingRuleStatus(r.id,!r.isActive);await refresh()})}>{r.isActive?'Desactivar':'Activar'}</Btn></div></article>)}<h3>Campañas de bonos</h3>{bonusCampaigns.map(b=><article key={b.id}><strong>{b.name} • {b.isActive?'ACTIVA':'INACTIVA'}</strong><p>{b.targetTrips} viajes → ${Number(b.rewardAmount).toFixed(2)}</p><small>{new Date(b.startsAt).toLocaleString()} — {new Date(b.endsAt).toLocaleString()}</small><div className="actions"><Btn onClick={()=>run(async()=>{await adminApi.bonusStatus(b.id,!b.isActive);await refresh()})}>{b.isActive?'Desactivar':'Activar'}</Btn></div></article>)}</section>}
 {tab==='risk'&&<section className="panel"><h3>Fraud & Risk</h3><p>El score automático abre casos para revisión. No suspende cuentas por sí solo; las restricciones y suspensiones requieren una decisión administrativa.</p>{riskCases.map(c=><article key={c.id}><strong>{c.level} • Score {c.scoreAtOpen} • {c.status}</strong><p>{c.user.email} • {c.user.role}</p><small>Score actual: {c.user.riskScore} • Nivel actual: {c.user.riskLevel}</small><div className="actions"><Btn onClick={()=>openRisk(c.userId)}>Ver señales</Btn><Btn onClick={()=>reviewRisk(c.id,'WATCH')}>Observar</Btn><Btn onClick={()=>reviewRisk(c.id,'RESTRICT')}>Restringir 24h</Btn><Btn onClick={()=>reviewRisk(c.id,'CLEAR')}>Limpiar</Btn><Btn danger onClick={()=>reviewRisk(c.id,'SUSPEND')}>Suspender</Btn></div></article>)}{selectedRisk&&<article className="monitor"><h3>Perfil de riesgo</h3><p>{selectedRisk.email} • Score {selectedRisk.riskScore} • {selectedRisk.riskLevel}</p><p>Señales: {selectedRisk.signals?.length||0} • Casos: {selectedRisk.cases?.length||0} • Dispositivos: {selectedRisk.devices?.length||0}</p>{selectedRisk.signals?.slice(0,10).map((s:any)=><p key={s.id}><strong>{s.type}</strong> +{s.weight} • {new Date(s.createdAt).toLocaleString()}</p>)}</article>}</section>}
 {tab==='refunds'&&<section className="panel"><h3>Reembolsos y disputas</h3>{refunds.map(r=><article key={r.id}><strong>{r.status}</strong><p>{r.reason}</p><small>Solicitado: {r.amountRequested?`$${Number(r.amountRequested).toFixed(2)}`:'revisión completa'}</small><div className="actions"><Btn onClick={()=>setRefund(r.id,'UNDER_REVIEW')}>Revisar</Btn><Btn onClick={()=>setRefund(r.id,'APPROVED')}>Aprobar</Btn><Btn onClick={()=>setRefund(r.id,'PROCESSED')}>Procesar en Stripe</Btn><Btn danger onClick={()=>setRefund(r.id,'REJECTED')}>Rechazar</Btn></div></article>)}</section>}
 {tab==='audit'&&<section className="panel"><h3>Audit Log</h3>{audit.map(a=><article key={a.id}><strong>{a.action}</strong><p>{a.entityType} • {a.entityId||'—'}</p><small>{new Date(a.createdAt).toLocaleString()}</small></article>)}</section>}
 </main></div>
}
