import React,{useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,SafeAreaView,ScrollView,Share,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import MapView,{Marker,Polyline} from 'react-native-maps';
import * as Location from 'expo-location';
import {initStripe,initPaymentSheet,presentPaymentSheet} from '@stripe/stripe-react-native';
import {API_URL,passengerApi,setAuthToken} from './src/api';
import {registerForUrRidePush} from './src/notifications';

type Coord={latitude:number;longitude:number};
const Field=({label,value,onChangeText,secureTextEntry,placeholder}:any)=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value} onChangeText={onChangeText} secureTextEntry={secureTextEntry} placeholder={placeholder} autoCapitalize="none"/></View>;
const Button=({title,onPress,secondary=false,disabled=false}:any)=><TouchableOpacity style={[s.button,secondary&&s.secondary,disabled&&s.disabled]} onPress={onPress} disabled={disabled}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{title}</Text></TouchableOpacity>;

export default function App(){
 const[email,setEmail]=useState('passenger@uride.local'),[password,setPassword]=useState('Password123!'),[user,setUser]=useState<any>(null);
 const[supportText,setSupportText]=useState(''),[lostItemText,setLostItemText]=useState(''),[refundReason,setRefundReason]=useState(''),[tickets,setTickets]=useState<any[]>([]),[trustedName,setTrustedName]=useState(''),[trustedPhone,setTrustedPhone]=useState(''),[tip,setTip]=useState('0'),[rating,setRating]=useState('5'),[scheduleAt,setScheduleAt]=useState(''),[returnScheduleAt,setReturnScheduleAt]=useState(''),[favorites,setFavorites]=useState<any[]>([]),[selectedFavorite,setSelectedFavorite]=useState(''),[upcoming,setUpcoming]=useState<any[]>([]),[pickup,setPickup]=useState<Coord>({latitude:26.7153,longitude:-80.0534}),[destination,setDestination]=useState<Coord>({latitude:26.7067,longitude:-80.0514});
 const[pickupAddress,setPickupAddress]=useState('Pickup'),[destinationAddress,setDestinationAddress]=useState('Destination'),[destinationQuery,setDestinationQuery]=useState('');
 const[route,setRoute]=useState<any>(null),[quote,setQuote]=useState<any>(null),[trip,setTrip]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const run=async(fn:()=>Promise<void>)=>{try{setBusy(true);setMessage('');await fn()}catch(e:any){setMessage(e.message||'Unexpected error')}finally{setBusy(false)}};
 const login=()=>run(async()=>{const r=await passengerApi.login(email,password);if(r.user.role!=='PASSENGER')throw new Error('Esta cuenta no es Passenger');setAuthToken(r.accessToken);setUser(r.user);const push=await registerForUrRidePush(r.user.id,passengerApi.registerPushDevice,'PASSENGER');if(push.registered&&push.token)await passengerApi.registerRiskDevice({userId:r.user.id,deviceId:push.token,platform:'MOBILE'});if(!push.registered)setMessage(push.reason==='EAS_PROJECT_ID_REQUIRED'?'Push listo; falta configurar EAS projectId para este build.':'Notificaciones push no autorizadas en este dispositivo.')});
 const register=()=>run(async()=>{const r=await passengerApi.register({email,password,firstName:'URide',lastName:'Passenger',preferredLanguage:'es'});setAuthToken(r.accessToken);setUser(r.user);const push=await registerForUrRidePush(r.user.id,passengerApi.registerPushDevice,'PASSENGER');if(push.registered&&push.token)await passengerApi.registerRiskDevice({userId:r.user.id,deviceId:push.token,platform:'MOBILE'});if(!push.registered)setMessage('Cuenta creada. Push requiere un development/release build y EAS projectId configurado.')});
 const loadRoute=async(p=pickup,d=destination)=>{const r=await passengerApi.route(p,d);setRoute(r);setQuote(await passengerApi.quote({serviceType:'STANDARD',estimatedMiles:r.distanceMiles,estimatedMinutes:r.durationMinutes}));return r};
 const useMyLocation=()=>run(async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')throw new Error('Necesitamos permiso de ubicación.');const loc=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});const c={latitude:loc.coords.latitude,longitude:loc.coords.longitude};setPickup(c);const rev=await Location.reverseGeocodeAsync(c);const a=rev[0];setPickupAddress(a?[a.name,a.street,a.city,a.region].filter(Boolean).join(', '):'Mi ubicación actual');await loadRoute(c,destination)});
 const searchDestination=()=>run(async()=>{if(!destinationQuery.trim())throw new Error('Escribe una dirección');const hits=await Location.geocodeAsync(destinationQuery.trim());if(!hits.length)throw new Error('No encontré esa dirección');const c={latitude:hits[0].latitude,longitude:hits[0].longitude};setDestination(c);setDestinationAddress(destinationQuery.trim());await loadRoute(pickup,c)});
 const mapDestination=(c:Coord)=>run(async()=>{setDestination(c);const rev=await Location.reverseGeocodeAsync(c);const a=rev[0];setDestinationAddress(a?[a.name,a.street,a.city,a.region].filter(Boolean).join(', '):'Destino seleccionado');await loadRoute(pickup,c)});
 const requestRide=()=>run(async()=>{if(!user)throw new Error('Inicia sesión primero');const r=route||await loadRoute();let scheduledFor:any=undefined;if(scheduleAt.trim()){const d=new Date(scheduleAt.trim());if(Number.isNaN(d.getTime()))throw new Error('Fecha inválida. Usa formato 2026-09-03T09:30:00-04:00');scheduledFor=d.toISOString()}const created=await passengerApi.createTrip({passengerUserId:user.id,serviceType:'STANDARD',pickupAddress,pickupLat:pickup.latitude,pickupLng:pickup.longitude,destinationAddress,destinationLat:destination.latitude,destinationLng:destination.longitude,estimatedMiles:r.distanceMiles,estimatedMinutes:r.durationMinutes,scheduledFor,preferredDriverProfileId:selectedFavorite||undefined});setTrip(created);if(created.status==='SCHEDULED')setMessage('Viaje programado correctamente')});
 const refreshTrip=async()=>{if(!trip?.id)return;try{setTrip(await passengerApi.getTrip(trip.id))}catch{}};
 const cancelRide=()=>run(async()=>{if(!trip?.id||!user)return;await passengerApi.cancelTrip(trip.id,user.id);await refreshTrip()});
 const rate=()=>run(async()=>{if(!trip?.id||!user)return;await passengerApi.rateTrip(trip.id,user.id,Number(rating)||5);setMessage('Calificación guardada')});
 const favorite=()=>run(async()=>{if(!trip?.id||!user)return;await passengerApi.favoriteDriver(trip.id,user.id);setMessage('Conductor agregado a favoritos')});
 const returnWithDriver=()=>run(async()=>{if(!trip?.id||!user)return;const t=await passengerApi.returnTrip(trip.id,user.id);setTrip(t);setPickup({latitude:t.pickupLat,longitude:t.pickupLng});setDestination({latitude:t.destinationLat,longitude:t.destinationLng});setPickupAddress(t.pickupAddress);setDestinationAddress(t.destinationAddress);setMessage('Regreso solicitado con preferencia por el mismo conductor')});
 const scheduleReturn=()=>run(async()=>{if(!trip?.id||!user||!returnScheduleAt.trim())throw new Error('Escribe fecha y hora de regreso');const d=new Date(returnScheduleAt.trim());if(Number.isNaN(d.getTime()))throw new Error('Fecha inválida');const t=await passengerApi.scheduleReturn(trip.id,user.id,d.toISOString());setMessage(`Regreso programado: ${new Date(t.scheduledFor).toLocaleString()}`)});
 const loadReservations=()=>run(async()=>{if(!user)return;setFavorites(await passengerApi.favorites(user.id));setUpcoming(await passengerApi.upcoming(user.id));const rs=await passengerApi.reminders(user.id);if(rs.length)setMessage(rs.map((r:any)=>r.message).join('\n'))});

 const openSupport=()=>run(async()=>{if(!user)throw new Error('Inicia sesión');if(!supportText.trim())throw new Error('Describe el problema');const t=await passengerApi.createSupportTicket({tripId:trip?.id||undefined,requesterUserId:user.id,category:'TRIP',subject:'Ayuda con mi viaje',description:supportText.trim()});setMessage(`Caso abierto: ${t.id}`);setSupportText('')});
 const loadTickets=()=>run(async()=>{if(!user)return;setTickets(await passengerApi.myTickets(user.id))});
 const reportLost=()=>run(async()=>{if(!user||!trip?.id)throw new Error('Selecciona un viaje');if(!lostItemText.trim())throw new Error('Describe el objeto');const item=await passengerApi.reportLostItem({tripId:trip.id,reporterUserId:user.id,itemType:'OTHER',description:lostItemText.trim()});setMessage(`Objeto perdido reportado: ${item.id}`);setLostItemText('')});
 const refund=()=>run(async()=>{if(!user||!trip?.id)throw new Error('Selecciona un viaje');if(!refundReason.trim())throw new Error('Explica el motivo');const r=await passengerApi.requestRefund({tripId:trip.id,requesterUserId:user.id,reason:refundReason.trim()});setMessage(`Solicitud de reembolso: ${r.status}`);setRefundReason('')});
 const saveTrusted=()=>run(async()=>{if(!user)throw new Error('Inicia sesión');if(!trustedName.trim()||!trustedPhone.trim())throw new Error('Nombre y teléfono son requeridos');await passengerApi.addTrustedContact({userId:user.id,name:trustedName.trim(),phone:trustedPhone.trim(),isPrimary:true});setMessage('Contacto de confianza guardado')});
 const sos=()=>run(async()=>{if(!trip?.id||!user)throw new Error('No hay viaje activo');await passengerApi.sos(trip.id,{reporterUserId:user.id,lat:pickup.latitude,lng:pickup.longitude,message:'SOS activado por pasajero'});setMessage('SOS registrado. En una versión de producción esto también alertará al centro de seguridad y contactos autorizados.')});
 const reportSafety=()=>run(async()=>{if(!trip?.id||!user)return;await passengerApi.reportIncident(trip.id,{reporterUserId:user.id,type:'OTHER',message:'Incidente reportado por pasajero'});setMessage('Incidente de seguridad reportado')});
 const askAi=()=>run(async()=>{if(!user)throw new Error('Inicia sesión');if(!aiQuestion.trim())throw new Error('Escribe una pregunta');const r=await passengerApi.aiAssist({userId:user.id,tripId:trip?.id,message:aiQuestion.trim()});setAiAnswer(r.answer);if(r.requiresHumanAction)setMessage('Esta acción requiere el flujo autorizado de URide o un agente humano.')});
 const shareRide=()=>run(async()=>{if(!trip?.id||!user)return;const link=await passengerApi.createSafetyShareLink(trip.id,user.id);const url=`${API_URL}${link.sharePath}`;await Share.share({message:`Sigue mi viaje URide: ${url}`});setMessage(`Enlace seguro creado hasta ${new Date(link.expiresAt).toLocaleTimeString()}`)});
 const changeDestination=()=>run(async()=>{if(!trip?.id)throw new Error('No hay viaje activo');if(!['DRIVER_ASSIGNED','DRIVER_ARRIVING','DRIVER_ARRIVED','IN_PROGRESS'].includes(trip.status))throw new Error('El destino solo puede cambiarse durante un viaje activo');const r=await loadRoute(pickup,destination);await passengerApi.changeDestination(trip.id,{destinationAddress, destinationLat:destination.latitude,destinationLng:destination.longitude,estimatedMiles:r.distanceMiles,estimatedMinutes:r.durationMinutes});await refreshTrip();setMessage('Destino actualizado y conductor notificado')});
 const pay=()=>run(async()=>{if(!trip?.id)return;const key=`passenger-${trip.id}-${Number(tip)||0}`;const r=await passengerApi.createPaymentIntent(trip.id,key,Number(tip)||0);if(!r.publishableKey)throw new Error('Falta STRIPE_PUBLISHABLE_KEY en la API');await initStripe({publishableKey:r.publishableKey,merchantIdentifier:'merchant.com.uride.passenger'});const sheet=await initPaymentSheet({merchantDisplayName:'URide',paymentIntentClientSecret:r.clientSecret,allowsDelayedPaymentMethods:false,defaultBillingDetails:{email:user?.email}});if(sheet.error)throw new Error(sheet.error.message);const shown=await presentPaymentSheet();if(shown.error)throw new Error(shown.error.message);const synced=await passengerApi.syncPayment(r.payment.id);await refreshTrip();setMessage(`Pago Stripe: ${synced?.status||'procesando'}`)});
 useEffect(()=>{loadRoute().catch(()=>{})},[]);
 useEffect(()=>{if(!trip?.id||trip.status==='COMPLETED')return;const timer=setInterval(refreshTrip,2500);return()=>clearInterval(timer)},[trip?.id,trip?.status]);
 const driver=trip?.locations?.[0]?{latitude:trip.locations[0].lat,longitude:trip.locations[0].lng}:null;
 const region=useMemo(()=>({latitude:(pickup.latitude+destination.latitude)/2,longitude:(pickup.longitude+destination.longitude)/2,latitudeDelta:Math.max(.03,Math.abs(pickup.latitude-destination.latitude)*2.8),longitudeDelta:Math.max(.03,Math.abs(pickup.longitude-destination.longitude)*2.8)}),[pickup,destination]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.brand}>URIDE</Text><Text style={s.subtitle}>Passenger • MVP v1.0.0 Pilot</Text><View style={s.notice}><Text style={s.noticeText}>API: {API_URL}</Text></View>
 {!user?<View style={s.card}><Text style={s.title}>Tu cuenta</Text><Field label="Correo" value={email} onChangeText={setEmail}/><Field label="Contraseña" value={password} onChangeText={setPassword} secureTextEntry/><Button title="Iniciar sesión" onPress={login}/><Button title="Crear pasajero de prueba" onPress={register} secondary/></View>:<View style={s.card}><Text style={s.title}>Hola, pasajero</Text><Text style={s.muted}>{user.email}</Text></View>} {user&&<View style={s.card}><Text style={s.title}>Seguridad</Text><Field label="Contacto de confianza" value={trustedName} onChangeText={setTrustedName}/><Field label="Teléfono" value={trustedPhone} onChangeText={setTrustedPhone}/><Button title="Guardar contacto de confianza" onPress={saveTrusted} secondary/></View>}
 <View style={s.card}><Text style={s.title}>¿A dónde vas?</Text><Field label="Buscar destino" value={destinationQuery} onChangeText={setDestinationQuery} placeholder="Ej. Palm Beach International Airport"/><Button title="Buscar dirección" onPress={searchDestination}/><Button title="Usar mi ubicación como recogida" onPress={useMyLocation} secondary/><MapView style={s.map} region={region} onPress={e=>mapDestination(e.nativeEvent.coordinate)} showsUserLocation><Marker coordinate={pickup} title="Recogida" pinColor="green"/><Marker coordinate={destination} title="Destino"/>{driver&&<Marker coordinate={driver} title="Tu conductor" pinColor="gold"/>}{route?.geometry?.length>1&&<Polyline coordinates={route.geometry} strokeWidth={5}/>}</MapView><Text style={s.detail}>Recogida: {pickupAddress}</Text><Text style={s.detail}>Destino: {destinationAddress}</Text>{route&&<View style={s.routeCard}><Text style={s.routeStrong}>{Number(route.distanceMiles).toFixed(1)} mi • ~{route.durationMinutes} min</Text><Text style={s.muted}>Ruta: {route.provider}</Text></View>}{quote&&<View style={s.fare}><Text style={s.fareLabel}>Precio estimado</Text><Text style={s.fareValue}>${Number(quote.estimatedFare).toFixed(2)}</Text></View>}<Field label="Programar para (opcional)" value={scheduleAt} onChangeText={setScheduleAt} placeholder="2026-09-03T09:30:00-04:00"/>{favorites.length>0&&<View style={s.routeCard}><Text style={s.routeStrong}>Conductor favorito para esta reserva</Text>{favorites.map((f:any)=><TouchableOpacity key={f.id} onPress={()=>setSelectedFavorite(selectedFavorite===f.driverProfileId?'':f.driverProfileId)}><Text style={s.detail}>{selectedFavorite===f.driverProfileId?'✓ ':'○ '}{f.driverProfile.firstName} {f.driverProfile.lastName}</Text></TouchableOpacity>)}</View>}<Button title={scheduleAt.trim()?"Programar URide":"Solicitar URide"} onPress={requestRide} disabled={!user||!route} secondary/><Button title="Mis reservas y favoritos" onPress={loadReservations} disabled={!user}/>{upcoming.length>0&&<View style={s.routeCard}>{upcoming.map((u:any)=><Text key={u.id} style={s.detail}>Reserva: {new Date(u.scheduledFor).toLocaleString()} • {u.destinationAddress}</Text>)}</View>}</View>
 {trip&&<View style={s.card}><Text style={s.title}>Tu viaje</Text><Text style={s.status}>{String(trip.status).replaceAll('_',' ')}</Text><Text style={s.muted}>Viaje: {trip.id}</Text>{trip.vehicle&&<Text style={s.detail}>{trip.vehicle.color} {trip.vehicle.make} {trip.vehicle.model} • {trip.vehicle.plate}</Text>}{driver&&<Text style={s.detail}>Conductor GPS: {driver.latitude.toFixed(5)}, {driver.longitude.toFixed(5)}</Text>}<Button title="Actualizar estado" onPress={refreshTrip} secondary/>{!['COMPLETED','CANCELLED','NO_SHOW'].includes(trip.status)&&<><Button title="SOS" onPress={sos}/><Button title="Reportar incidente" onPress={reportSafety}/><Button title="Compartir estado del viaje" onPress={shareRide} secondary/></>}{['DRIVER_ASSIGNED','DRIVER_ARRIVING','DRIVER_ARRIVED','IN_PROGRESS'].includes(trip.status)&&<Button title="Actualizar destino del viaje" onPress={changeDestination} secondary/>}{!['COMPLETED','CANCELLED','NO_SHOW'].includes(trip.status)&&<Button title="Cancelar viaje" onPress={cancelRide}/>}{trip.status==='COMPLETED'&&<><Field label="Propina ($)" value={tip} onChangeText={setTip}/><Field label="Calificación (1-5)" value={rating} onChangeText={setRating}/><Button title="Calificar conductor" onPress={rate} secondary/><Button title="Agregar conductor a favoritos" onPress={favorite}/><Button title="Regresar con este conductor" onPress={returnWithDriver} secondary/><Field label="Programar regreso" value={returnScheduleAt} onChangeText={setReturnScheduleAt} placeholder="2026-09-03T18:00:00-04:00"/><Button title="Programar regreso con este conductor" onPress={scheduleReturn}/></>}{trip.status==='COMPLETED'&&!trip.payments?.some((p:any)=>p.status==='SUCCEEDED')&&<Button title="Pagar viaje con Stripe" onPress={pay}/>} {['CANCELLED','NO_SHOW'].includes(trip.status)&&trip.cancellationFeeStatus==='PENDING'&&<Button title={`Pagar cargo $${Number(trip.cancellationFee||0).toFixed(2)} con Stripe`} onPress={pay}/>} {trip.payments?.[0]&&<Text style={s.detail}>Pago: {trip.payments[0].status}</Text>}</View>}
 {user&&<View style={s.card}><Text style={s.title}>URide AI</Text><Text style={s.muted}>Asistente de información. No ejecuta pagos, reembolsos, suspensiones ni acciones de emergencia.</Text><Field label="Pregúntale a URide AI" value={aiQuestion} onChangeText={setAiQuestion} placeholder="¿Dónde está mi conductor?"/><Button title="Preguntar a URide AI" onPress={askAi} secondary/>{!!aiAnswer&&<Text style={s.detail}>{aiAnswer}</Text>}</View>}
 <View style={s.card}><Text style={s.title}>Ayuda y soporte</Text><Field label="Describe tu problema" value={supportText} onChangeText={setSupportText} placeholder="Cobro, viaje, conductor, cancelación..."/><Button title="Abrir caso de soporte" onPress={openSupport} disabled={!user}/><Button title="Mis casos" onPress={loadTickets} secondary/>{tickets.slice(0,3).map((t:any)=><Text key={t.id} style={s.detail}>Caso {t.id.slice(0,8)} • {t.category} • {t.status}</Text>)}{trip&&<><Field label="Objeto perdido" value={lostItemText} onChangeText={setLostItemText} placeholder="Ej. teléfono negro en asiento trasero"/><Button title="Reportar objeto perdido" onPress={reportLost}/><Field label="Reembolso / disputa" value={refundReason} onChangeText={setRefundReason} placeholder="Explica el cobro o problema"/><Button title="Solicitar revisión de reembolso" onPress={refund} secondary/></>}</View>
 {busy&&<ActivityIndicator size="large"/>}{!!message&&<Text style={s.message}>{message}</Text>}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f5f2'},container:{padding:20,gap:16},brand:{fontSize:38,fontWeight:'900',letterSpacing:4,color:'#111'},subtitle:{color:'#777',marginTop:-8},notice:{backgroundColor:'#fff4cc',padding:10,borderRadius:10},noticeText:{fontSize:12,color:'#5b4800'},card:{backgroundColor:'#fff',padding:18,borderRadius:18,gap:12},title:{fontSize:20,fontWeight:'800',color:'#111'},field:{gap:6},label:{fontSize:12,fontWeight:'700',color:'#666'},input:{borderWidth:1,borderColor:'#ddd',borderRadius:12,paddingHorizontal:12,paddingVertical:11,fontSize:16,color:'#111'},button:{backgroundColor:'#111',borderRadius:12,padding:14,alignItems:'center'},secondary:{backgroundColor:'#d6ac35'},buttonText:{color:'#fff',fontWeight:'800'},secondaryText:{color:'#111'},disabled:{opacity:.45},fare:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'#f7f3e7',padding:14,borderRadius:12},fareLabel:{fontWeight:'700'},fareValue:{fontSize:26,fontWeight:'900'},status:{fontSize:22,fontWeight:'900',color:'#9a7512'},muted:{color:'#777'},detail:{fontSize:14,color:'#222'},message:{backgroundColor:'#fff',padding:12,borderRadius:10,color:'#9a251a'},map:{height:350,borderRadius:16},routeCard:{backgroundColor:'#f1f1ed',padding:12,borderRadius:12},routeStrong:{fontSize:18,fontWeight:'800'}});
